version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elasticsearch/config/GeoLite2-City-Updated.mmdb
        target: /usr/share/elasticsearch/config/ingest-geoip/GeoLite2-City-Updated.mmdb
        read_only: true
      - type: volume
        source: /data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx16384m -Xms16384m"
      ELASTIC_PASSWORD: digiercdn*
      discovery.type: single-node
    networks:
      - elk
    logging:
      driver: "json-file"
      options:
       max-size: 10m
       max-file: "3"

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5051:5051/tcp"
      - "5051:5051/udp"
      - "9600:9600"
      - "443:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
       max-size: 10m
       max-file: "3"
  
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
       max-size: 10m
       max-file: "3"

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
